version: "3.9"
services:
    db:
        image: mongo:4.4.15
        container_name: socialize-db
        ports:
            - ${MONGO_PORT:-27017}:27017
    backend:
        image: socialize-backend:latest
        container_name: socialize-backend
        ports:
            - ${SERVER_PORT:-8080}:8080
        depends_on:
            - db
        links:
            - db
    frontend:
        image: socialize-frontend:latest
        container_name: socialize-frontend
        ports:
            - ${FRONTEND_PORT:-3000}:3000
        depends_on:
            - backend
        links:
            - backend
